version: '3.4'
services:
  
  mcp-tesla:
    image: mcp-tesla
    build: .
    restart: on-failure
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    ports:
      - "8084:80"
