apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mcp
  name: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mcp
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        io.kompose.service: mcp
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: app-manager
      nodeSelector:
        kubernetes.io/hostname: myteslamate-prod      
      containers:
        - name: mcp
          image: "{{ .Values.global.image }}:{{ .Values.global.tag }}"
          env:
            - name: PORT
              value: "80"
          envFrom:
            - configMapRef:
                name: mcp-config
          ports:
            - containerPort: 80
          resources: {}
              mountPath: /root/.kube # Path in the container
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mcp
  name: mcp
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: mcp